apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ${PROJECT}-ingress
spec:
  rules:
    - host: ${PROJECT}.sit.yumimiao.cn
      http:
        paths:
          - backend:
              serviceName: ${PROJECT}-svc
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT}
  labels:
    app: ${PROJECT}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ${PROJECT}
  template:
    metadata:
      labels:
        app: ${PROJECT}
    spec:
      imagePullSecrets:
        - name: aliyun-docker-registry
      containers:
        - name: ${PROJECT}
          image: registry.cn-chengdu.aliyuncs.com/lura/${PROJECT}:build-${BUILD_NUMBER}
          env:
          - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR
            value: 192.168.31.110
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
#      tolerations:
#        - key: node-role.kubernetes.io/master
#          effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT}-svc
  namespace: default
  labels:
    app: ${PROJECT}-svc
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ${PROJECT}
  type: NodePort
