server:
  port: 8013
  servlet:
    context-path: /auth
spring:
  application:
    name: lura-framework-auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://${DB_HOST:localhost}:3306/lura_framework?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
  cloud:
#    nacos:
#      discovery:
#        group: LURA-FRAMEWORK
    sentinel:
      datasource:
        flow:
          nacos:
            server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR:localhost}:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SYSTEM
            rule-type: flow
      transport:
        port: 8719
        dashboard: http://${SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR:localhost}:8858
      http-method-specify: true
  jpa:
    hibernate:
      ddl-auto: update
